experiments:
  - task:
      name: autotagging
      type: multilabel_classification
      feature_aggregation: mean
    datasets:
      - name: magnatagatune
        type: custom
        dir: data/magnatagatune/
        split_type: single
        deformations:
          - - type: AddGaussianSNR
              params:
                min_snr_in_db: 15
                max_snr_in_db: 15
                p: 1
          - - type: AddGaussianSNR
              params:
                min_snr_in_db: 0
                max_snr_in_db: 0
                p: 1
          - - type: Gain
              params:
                min_gain_in_db: -12
                max_gain_in_db: -12
                p: 1
    features:
      #- vggish-audioset
      #- clmr-v2
      #- mert-v1-95m-6
      - mfcc
    feature_parameters:
      mfcc:
        n_mfcc: 16
        n_mels: 40
        fmin: 20
        fmax: 8000
        dct_type: 2
        norm: ortho
        window_size_ms: 20  # Tamanho da janela em milissegundos
    probes:
      - type: classifier
        emb_dim_reduction: False
        emb_shape: infer
        hidden_units: []
        output_activation: sigmoid
        weight_decay: 1.0e-5
        # optimizer
        optimizer: adam
        learning_rate: 1.0e-3
        # training
        batch_size: 1083
        epochs: 100
        patience: 10
        train_sampling: random
      - type: classifier
        emb_dim_reduction: False
        emb_shape: infer
        hidden_units: [infer]
        output_activation: sigmoid
        weight_decay: 1.0e-5
        # optimizer
        optimizer: adam
        learning_rate: 1.0e-3
        # training
        batch_size: 1083
        epochs: 100
        patience: 10
        train_sampling: random
      - type: classifier
        emb_dim_reduction: False
        emb_shape: infer
        hidden_units: [256, 128]
        output_activation: sigmoid
        weight_decay: 1.0e-5
        # optimizer
        optimizer: adam
        learning_rate: 1.0e-3
        # training
        batch_size: 1083
        epochs: 100
        patience: 10
        train_sampling: random
      
